language: java

jdk:
  - openjdk8

install:
  - cd spectre-parent
  - mvn clean install -DskipTests=true
  - cd ../spectre-common
  - mvn clean install -DskipTests=true
  - cd ../spectre-transport
  - mvn clean install -DskipTests=true
  - cd ../spectre-agent
  - mvn clean install -DskipTests=true
  - cd ../spectre-shell
  - mvn clean install -DskipTests=true
  - cd ..
  - rm -rf build
  - mkdir build
  - cp ./spectre-agent/target/spectre-agent-1.0.0.jar ./build/spectre-agent.jar
  - cp ./spectre-shell/target/spectre-shell-1.0.0.jar ./build/spectre-shell.jar
  - cp ./spectre-shell.* ./build/